### ISSUE TITLE
How to use with @ngtools/webpack and without angular.json?

### ISSUE THREAD

**Issue by Rush** [cyrilletuzi/vscode-typescript-angular-plugin#10]
My project is set up manually without angular.json. Is there a way to use this addon for a project without the angular.json file?

**Comment by cyrilletuzi** [comment]
We can't activate the extension for all projects, so the `angular.json` check is for that purpose.

If you have a custom environment, you'll need to do a manuel config:
- add `"plugins": { "name": "@angular/language-service" }` in your `compilerOptions` of `tsconfig.json`
- use the **project version** of TypeScript (*not* the VS Code one)
- no extension needed
