### ISSUE TITLE
Intellisense not be evaluated correctly when adding new attributes

### ISSUE THREAD

**Issue by cmeyertons** [cyrilletuzi/vscode-typescript-angular-plugin#2]
![image](https://user-images.githubusercontent.com/19917677/48716178-6256fa80-ebdc-11e8-8328-ed77b1696346.png)

in my component i have:
```
public dateChange(dateRange: IDateRange): void {
    this.effectiveStartDate = dateRange.startDate;
    this.effectiveEndDate = dateRange.endDate;
  }
```

**Comment by cyrilletuzi** [comment]
@cmeyertons Isn't this the same as #5?

**Comment by cyrilletuzi** [comment]
Closing for house keeping purpose, as no reproduction has been provided. Feel free to add more information and I'll re-open the issue.
