### ISSUE TITLE
Moustache only works when padded by spaces

### ISSUE THREAD

**Issue by cmeyertons** [cyrilletuzi/vscode-typescript-angular-plugin#6]
No spaces:

![image](https://user-images.githubusercontent.com/19917677/48717295-b8c53880-ebde-11e8-9574-6fde8338925f.png)

Spaces:

![image](https://user-images.githubusercontent.com/19917677/48717332-caa6db80-ebde-11e8-87c5-4c2cc72ae956.png)

**Comment by cyrilletuzi** [comment]
@cmeyertons Can't reproduce this issue. Can you double check? Is the legacy extension disabled?

**Comment by cyrilletuzi** [comment]
@cmeyertons Another important question: what is the version of Angular in your project?

**Comment by cyrilletuzi** [comment]
Closing for house keeping purpose, as no reproduction has been provided. Feel free to add more information and I'll re-open the issue.
