### ISSUE TITLE
Update to @angular/language-service@7.1.0

### ISSUE THREAD

**Issue by cyrilletuzi** [cyrilletuzi/vscode-typescript-angular-plugin#8]
Planned.

Just waiting for an issue in Angular repo to be closed.

**Comment by Springrbua** [comment]
@cyrilletuzi Does the plugin bundle a language-service version or is it using the one you have installed localy?
I am asking, because the official vs-code plugin (which is not actively maintained) is using a bundled (and often outdated verrsion).
Thanks for your effort, I will probably try this one as soon as I switch to Angular 7.

**Comment by cyrilletuzi** [comment]
@Springrbua It uses a bundled `@angular/language-service`, as it how this type of extensions are designed to work.

You can use your project `@angular/language-service` by adding it in your `tsconfig.json `, but it will imply to use the project version of TypeScript (instead of the VS Code one). This solution has its own drawbacks: the TypeScript version of Angular projects is often outdated, so you won't benefit of the latest quick fixes added in last version of TS.

Issue fixed and released in 1.1.0.

**Comment by Springrbua** [comment]
Thank you for the informations.
I actually want to use the bundled version cause of incompatibilities.
There are multiple people working on a multi-app project, so we need to ensure, that everyone is using the same versions.
I would like to use the language-service as "normal" typeacript plugin, nut this has one major drawback:
It does only support inline-templates.
I've read your opinion on this and I agree with most of your points, but I like to keep template and component separate.
So what I am looking for is actually only a plugin, which enables the typescript-server (language-service) for html-files

**Comment by Springrbua** [comment]
Thank you for the informations, I'll keep this plugin in my mind :)
